"""add room to orders

Revision ID: c5801e2208ac
Revises: b25ec253e54d
Create Date: 2026-09-15 10:29:38.728835

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c5801e2208ac'
down_revision: str | Sequence[str] | None = 'b25ec253e54d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'hotel_rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'room_id')
    # ### end Alembic commands ###
